server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rubenmt99/MicroserviciosCloudImpl.git
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
      #enabled: false

  security:
    user:
      name: root
      password: s3cr3t

